import { StyleSheet, Platform } from 'react-native';

const colors = {
  primary: {
    main: '#4F46E5',
    dark: '#312E81',
    light: '#4338CA',
  },
  secondary: '#5856D6',
  danger: '#FF3B30',
  success: '#34C759',
  text: {
    primary: '#1A1A1A',
    secondary: '#666666',
  },
  background: {
    primary: '#FFFFFF',
    secondary: '#F8F9FA',
    overlay: 'rgba(0, 0, 0, 0.5)',
    transparent: 'rgba(255, 255, 255, 0.1)',
  },
  border: '#E8E8E8',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  scrollView: {
    flex: 1,
    backgroundColor: colors.background.primary,
  },
  // Header Styles
  header: {
    padding: 24,
    paddingTop: Platform.OS === 'ios' ? 20 : 16,
    paddingBottom: 16,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  headerTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: colors.background.primary,
    letterSpacing: -0.5,
  },
  betaBadge: {
    overflow: 'hidden',
    borderRadius: 8,
  },
  betaBadgeGradient: {
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  betaText: {
    color: colors.background.primary,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  notificationButton: {
    position: 'relative',
    padding: 6,
    backgroundColor: colors.background.transparent,
    borderRadius: 10,
  },
  notificationBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    backgroundColor: colors.danger,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#4A55A2',
  },
  notificationCount: {
    color: colors.background.primary,
    fontSize: 10,
    fontWeight: '700',
  },
  profileButton: {
    padding: 6,
    backgroundColor: colors.background.transparent,
    borderRadius: 10,
  },
  // Welcome Section
  welcomeContainer: {
    marginBottom: 24,
  },
  welcomeTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.background.primary,
    marginBottom: 6,
  },
  welcomeText: {
    fontSize: 15,
    color: colors.background.primary,
    opacity: 0.9,
    lineHeight: 20,
  },
  // Quick Access Section
  quickAccessGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  quickAccessButton: {
    flex: 1,
    backgroundColor: colors.background.transparent,
    borderRadius: 14,
    padding: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.background.transparent,
  },
  quickAccessIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  quickAccessText: {
    color: colors.background.primary,
    fontSize: 13,
    fontWeight: '600',
  },
  // Common Section Styles
  sectionWrapper: {
    backgroundColor: colors.background.primary,
    marginTop: 16,
    paddingHorizontal: 24,
  },
  sectionHeaderMain: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 0,
    height: 48,
    marginBottom: 12,
  },
  sectionTitleWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.text.primary,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  viewAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: colors.primary.main,
    borderRadius: 12,
    height: 36,
    alignSelf: 'center',
  },
  viewAllText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.background.primary,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  // Rest of your existing styles...
  modalContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1000,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.background.overlay,
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.background.primary,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '80%',
    paddingBottom: Platform.OS === 'ios' ? 34 : 24,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: '600',
    color: colors.text.primary,
    textAlign: 'center',
    flex: 1,
  },
  closeButton: {
    padding: 8,
    width: 40,
    alignItems: 'center',
  },
  modalScroll: {
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  dragHandle: {
    width: '100%',
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dragIndicator: {
    width: 40,
    height: 4,
    backgroundColor: '#E0E0E0',
    borderRadius: 2,
  },
  // Campaign Styles
  campaignsScrollContainer: {
    paddingRight: 12,
    paddingVertical: 8,
  },
  campaignCard: {
    width: 280,
    height: 200,
    marginRight: 16,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: colors.background.primary,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  campaignBackground: {
    width: '100%',
    height: '100%',
  },
  campaignBackgroundImage: {
    resizeMode: 'cover',
  },
  campaignGradient: {
    flex: 1,
    justifyContent: 'flex-end',
    padding: 20,
  },
  campaignCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  campaignTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.background.primary,
    flex: 1,
    marginRight: 12,
  },
  discountBadge: {
    backgroundColor: colors.danger,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  discountText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.background.primary,
  },
  campaignDescription: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.background.primary,
    opacity: 0.9,
    marginBottom: 16,
  },
  campaignFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginTop: 4,
  },
  priceContainer: {
    flexDirection: 'column',
  },
  campaignPrice: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.background.primary,
  },
  campaignOriginalPrice: {
    fontSize: 14,
    color: colors.background.primary,
    opacity: 0.7,
    textDecorationLine: 'line-through',
    marginTop: 2,
  },
  campaignMetaInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  daysLeftBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.background.transparent,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  daysLeftText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.background.primary,
  },
  // Campaign List Styles
  campaignListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  campaignThumbnail: {
    width: 80,
    height: 80,
    borderRadius: 8,
    marginRight: 12,
  },
  campaignListContent: {
    flex: 1,
  },
  campaignListHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  campaignListTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text.primary,
  },
  campaignListDescription: {
    fontSize: 14,
    color: colors.text.secondary,
  },
  campaignListFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  remainingDays: {
    fontSize: 14,
    color: colors.text.secondary,
  },
  stockCount: {
    fontSize: 14,
    color: colors.text.secondary,
  },
}); 